public enum PlayerAction
{
    SHOW_BUTTON_PROJECT,
    SHOW_BUTTON_NEW_PROJECT,
    SHOW_BUTTON_SOCIAL_MEDIA,
    SHOW_BUTTON_FIX_BUGS,
    SHOW_BUTTON_SLEEP,
    SHOW_BUTTON_RELAX,
    SHOW_BUTTON_COOK,
    NONE
}